name: lost_and_found
description: A placeholder Flutter app for Lost and Found
version: 0.0.1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
